apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::355947842119:role/UdacityFlaskDeployCBKubectlRole
      username: build  

    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::355947842119:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1O5JVCZSUJ9Y4
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-04T23:33:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1355"
  uid: 9e14d1fe-961a-47be-96f2-f5d6a760c320
